version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8
jobs:
  backend-check:
    <<: *defaults
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: cd backend && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: cd backend && npm run ci
  
  backend-deploy-staging:
    <<: *defaults
    steps:
      - checkout
      - run: sudo npm install --global --unsafe-perm now
      - run: cd backend && $(npm bin -g)/now --token $ZEIT_TOKEN --local-config now.staging.json --target production

  backend-deploy-production:
    <<: *defaults
    steps:
      - checkout
      - run: sudo npm install --global --unsafe-perm now
      - run: cd backend && $(npm bin -g)/now --token $ZEIT_TOKEN --local-config now.production.json --target production
      
workflows:
  version: 2
  backend-deploy:
    jobs:
      - backend-check
      - backend-deploy-staging:
          requires:
            - backend-check
          filters:
            branches:
              only: master
      - backend-deploy-production:
          requires:
            - backend-check
          filters:
            branches:
              only: production