version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8
jobs:
  check:
    <<: *defaults
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run ci
  
  deploy-staging:
    <<: *defaults
    steps:
      - checkout
      - run: sudo npm install --global --unsafe-perm now
      - run: $(npm bin -g)/now --token $ZEIT_TOKEN --local-config now.staging.json --target production
  deploy-production:
    <<: *defaults
    steps:
      - checkout
      - run: sudo npm install --global --unsafe-perm now
      - run: $(npm bin -g)/now --token $ZEIT_TOKEN --local-config now.production.json --target production
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - check
      - deploy-staging:
          requires:
            - check
          filters:
            branches:
              only: master
      - deploy-production:
          requires:
            - check
          filters:
            branches:
              only: production