version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8
jobs:
  deploy-staging:
    <<: *defaults
    steps:
      - checkout
      - run: sudo npm install --global --unsafe-perm now
      - run: $(npm bin -g)/now --token $ZEIT_TOKEN --local-config now.staging.json --target production
  deploy-production:
    <<: *defaults
    steps:
      - checkout
      - run: sudo npm install --global --unsafe-perm now
      - run: $(npm bin -g)/now --token $ZEIT_TOKEN --local-config now.production.json --target production
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: master
      - deploy-production:
          filters:
            branches:
              only: production